// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvT9mD9q52Xn9A1164EN82PCXpOW9JhBM',
    appId: '1:339701858953:android:491be7acc0f7aab7dbfc58',
    messagingSenderId: '339701858953',
    projectId: 'login-app-f9382',
    storageBucket: 'login-app-f9382.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfPQ_CX5mZCbEXCi9qhG-RN4MiYmj9me4',
    appId: '1:339701858953:ios:f82af427d04d1024dbfc58',
    messagingSenderId: '339701858953',
    projectId: 'login-app-f9382',
    storageBucket: 'login-app-f9382.appspot.com',
    androidClientId: '339701858953-jsb27pqq7q26gipc2hu7vv2v3b4cb31i.apps.googleusercontent.com',
    iosClientId: '339701858953-3d75b0o941k6mc2osc99e73a1b78r0u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );
}
